services:
  app_server:
    container_name: app_server
    build:
        context: .
        target: app_server
    image: app_server
    working_dir: /app
    command:
      - poetry run python -m botvov.main
    volumes:
      - ./botvov:/app/botvov
    ports:
      - "5000:5000"
    networks:
      - app_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['all']
              capabilities: [gpu]

  llm_serve:
    container_name: llm_serve
    build:
      context: .
      target: llm_serve
    volumes:
      - huggingface:/root/.cache/huggingface
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['all']
              capabilities: [gpu]
    networks:
      - app_network
    shm_size: '15gb'

  faster-whisper-server-cuda:
    container_name: speech2text
    build:
      context: .
      target: speech2text
    image: speech2text
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - ./models:/root/faster-whisper-server/models
    command: >
      bash -c "./ct2_converter.sh
      && uv run uvicorn faster_whisper_server.main:app"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['all']
              capabilities: [gpu]
              # If you have CDI feature enabled use the following instead
              # https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/cdi-support.html
              # https://docs.docker.com/reference/cli/dockerd/#enable-cdi-devices
              # - driver: cdi
              #   device_ids:
              #   - nvidia.com/gpu=all
    networks:
      - app_network

  text2speech:
    container_name: text2speech
    build: 
      context: .
      target: text2speech
    image: text2speech
    ports:
      - 6000:6000
    volumes:
      - ./text2speech:/app/text2speech
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    command: 
      - python -m text2speech.server
    networks:
      - app_network

volumes:
  huggingface:

networks:
  app_network: