version: '3.8'

services:
  app_server:
    container_name: app_server
    build:
        context: .
        target: app_server
    working_dir: /app
    command:
      - poetry run python -m botvov.main
    ports:
      - "5000:5000"
    networks:
      - app_network

  ollama:
    container_name: ollama
    build:
        context: .
        target: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    entrypoint:
      - /bin/bash
      - -c
      - |
        /app/init_llm.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    networks:
      - app_network

volumes:
  ollama:

networks:
  app_network:
