[tool.poetry]
name = "botvov"
version = "0.1.0"
description = "An AI assistant support answer questions and do tasks from user"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ollama = "^0.3.1"
qwen-agent = {extras = ["code-interpreter", "gui", "rag"], version = "^0.0.7"}
pydantic = "^2.8.2"
flask = "^3.0.3"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
